# Generated by Django 5.1.3 on 2024-12-02 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinic_id', models.AutoField(primary_key=True, serialize=False)),
                ('clinic_name', models.CharField(max_length=100)),
                ('clinic_phone_number', models.CharField(max_length=15)),
                ('clinic_address', models.TextField()),
                ('clinic_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insurance_id', models.AutoField(primary_key=True, serialize=False)),
                ('insurance_name', models.CharField(max_length=100)),
                ('policy_number', models.CharField(max_length=50)),
                ('coverage', models.FloatField()),
                ('premium', models.FloatField()),
                ('expiry_date', models.DateField()),
                ('no_of_dependents', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=100)),
                ('dosage', models.FloatField()),
                ('manufacture_date', models.DateField(default='2024-01-01')),
                ('expiry_date', models.DateField(default='2025-01-01')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('salary', models.FloatField()),
                ('bonuses', models.FloatField()),
                ('deductions', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pharmacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('pharmacy_name', models.CharField(max_length=100)),
                ('pharmacy_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('D_id', models.AutoField(primary_key=True, serialize=False)),
                ('D_Name', models.CharField(default='Unknown', max_length=100)),
                ('D_phone_number', models.CharField(max_length=15)),
                ('D_email', models.EmailField(max_length=254)),
                ('License_number', models.CharField(default='ABC12345', max_length=50)),
                ('Specialization', models.CharField(default='General', max_length=100)),
                ('clinic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(default='Unknown', max_length=10)),
                ('patient_phone_number', models.CharField(max_length=15)),
                ('patient_address', models.TextField()),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.insurance')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_phone_number', models.CharField(max_length=15)),
                ('employee_address', models.TextField()),
                ('job_title', models.CharField(max_length=100)),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('Prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('vaccination_id', models.AutoField(primary_key=True, serialize=False)),
                ('vaccination_name', models.CharField(max_length=100)),
                ('dosage', models.FloatField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
            ],
        ),
    ]
