# Generated by Django 5.1.3 on 2024-12-02 01:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_patient_condition_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date_prescribed',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage_instructions',
            field=models.TextField(default='Take as Prescribed'),
            preserve_default=False,
        ),
    ]
