# Generated by Django 5.1.3 on 2024-12-02 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_prescription_date_prescribed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date_prescribed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.pharmacy'),
        ),
    ]
