# Generated by Django 5.1.3 on 2024-12-02 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_prescription_date_prescribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pharmacy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinic.pharmacy'),
            preserve_default=False,
        ),
    ]
